### ISSUE TITLE
No generator for Rails 3.

### ISSUE THREAD

**Issue by gwarf** [cingel/mark_it_up#1]
Hi,
Thanks for this great plugin I'am using it on Rails 3.0.1 but it seems that there is no compatible generator for the controller, I had to manually "generate" the controller and the view, and add the required route.

Regards,
Baptiste

**Comment by cingel** [comment]
Thanks Baptiste, I haven't yet used it in Rails 3 app, so I didn't wrote generators. I will try to add them when I get time, or if you're interested you can write those generators and add them?

**Comment by gwarf** [comment]
OK, I will try to take a look at it as soon as possible.

**Comment by seocore** [comment]
Great, fork it let me know when you have anything interesting.
Thanks
Vlado

**Comment by gwarf** [comment]
Hi,
Yesterday I just discoverted that lexmag had already forked this project and commited some rails3 controllers related code at http://github.com/lexmag/mark_it_up/.
So...
But I think I will still try to do this (and also try to create a gem supporting rails 2 and 3) at least as an exercise.
Cheers,
Baptiste

**Comment by cingel** [comment]
That would be great! If you want I can add you as collaborator, and you can do all changes on cingel/mark_it_up.
Thanks
Vlado

**Comment by gwarf** [comment]
That would be nice, but let me first have something done before ;)
Once I will be on the way I will be pleased to be added as a collaborator :)

Cheers,
Baptise

**Comment by cingel** [comment]
Ok Baptiste. Let me know when you have something.

**Comment by gwarf** [comment]
I have something. ;)

This is just a first version of a rails 3 gem that was really quickly tested.

Cheers,
Baptiste

**Comment by cingel** [comment]
This looks great, I would like to merge it in my repo. If that is ok with you, please send me a pull request.

Thanks
Vlado

**Comment by gwarf** [comment]
So I think that know we can close this issue ;)
